# Generated by Django 6.0.2 on 2026-02-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100, unique=True)),
                ('motherboard', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_cores', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_threads', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_frequency_min', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_frequency_cur', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_frequency_max', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_slots', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_total', models.CharField(blank=True, max_length=50, null=True)),
                ('total_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('arch', models.CharField(blank=True, max_length=50, null=True)),
                ('desktop_env', models.CharField(blank=True, max_length=100, null=True)),
                ('window_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('kernel', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
