# Generated by Django 6.0.2 on 2026-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
