# Generated by Django 6.0.2 on 2026-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employees_systeminfo_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systeminfo',
            old_name='employee',
            new_name='employees',
        ),
    ]
