# Generated by Django 6.0.2 on 2026-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_employee_systeminfo_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='disks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
