# Generated by Django 6.0.2 on 2026-02-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systeminfo_disks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
